[WIP] 編集モードを欄外をクリックすることで解除できるようにした
whalepod/milelane-desktop pull request #101
Opened 2020-09-23 01:02 UTC by sanoyo

2020-09-23 12:21 UTC, MasashiFujiike requested changes

2020-09-23 12:21 UTC, MasashiFujiike commented on src/views/Root.vue
> +  mounted () {
自分で方針のところに書いておいてなんなんだけど、domのどれかに@click仕込んだ方がすっきりしそう。
preventDefaultはむしろTaskItemの親要素のクリックイベントに対して仕込むべきなので、そっちで @click.stop 的な書き方するのがいいかもです。

動かして確認もしてみますが、この実際だとおそらく編集モード中にinput要素をクリックしてもモード外れちゃう気がします

2020-09-23 12:53 UTC, sanoyo commented on src/views/Root.vue
> +  mounted () {
>動かして確認もしてみますが、この実際だとおそらく編集モード中にinput要素をクリックしてもモード外れちゃう気がします

編集モード中にinput要素をクリックしても、編集モードが外れないことは確認済みです！

2020-09-23 17:42 UTC, MasashiFujiike requested changes

2020-09-23 17:42 UTC, MasashiFujiike commented on src/components/task/TaskItem.vue
> +        @click.stop
[should]
`@click.stop` の対象は、3行目、 `class="task-item"` と同じオブジェクトを対象にしましょう。
ユーザーの体験としては、同じタスクをクリックして選択が外れてしまうのは期待と異なる動作になるはずなので、
そこまではイベントのバブルアップを止める対象としたいです。

2020-09-23 23:39 UTC, sanoyo commented on src/components/task/TaskItem.vue
> +        @click.stop
理解が足りてませんでした！
修正しましたので、ご確認ください！

2020-09-24 00:02 UTC, MasashiFujiike approved these changes
LGTM 👍

2020-09-24 00:04 UTC, merged